routes/web.php
<?php

use App\Http\Controllers\DocumentController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{Auth\ForgotPasswordController,
    BannerController,
    CarnetController,
    CertificadoController,
    EntidadesFormadoreasController,
    ExamenController,
    OperadoresController,
    CategoryController,
    AsistentController,
    FaqController,
    FrontController,
    GeneralController,
    LinkController,
    HorarioController,
    PartnerController,
    PcategoryController,
    CursosController,
    PostController,
    FormadoresController,
    TagController,
    TestimonialController,
    TeamController,
    UserController};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', [FrontController::class, 'home'])->name('homepage');
Route::post('/', [FrontController::class, 'subscribe'])->name('subscribe');
Route::get('about-us', [FrontController::class, 'about'])->name('about');
Route::get('quienes-somos', [FrontController::class, 'about2'])->name('about2');
Route::get('contact', [FrontController::class, 'contact'])->name('contact');
Route::get('entidades', [FrontController::class, 'entidades'])->name('entidades');
Route::get('testimonials', [FrontController::class, 'testi'])->name('testi');
Route::get('cursos', [FrontController::class, 'cursos'])->name('cursos');
Route::get('curso/{slug}', [FrontController::class, 'curso'])->name('curso');
Route::get('carnets', [FrontController::class, 'carnets'])->name('carnets');
Route::POST('searchcarnet', [FrontController::class, 'searchcarnet'])->name('searchcarnet');
Route::get('carnet/{slug}', [FrontController::class, 'carnet'])->name('carnet');
Route::get('partners', [FrontController::class, 'partners'])->name('partners');
Route::get('partner/{slug}', [FrontController::class, 'partner'])->name('partner');
Route::get('entidades_formadoras', [FrontController::class, 'entidades_formadoras'])->name('entidades_formadoras');
Route::get('entidade_formadora/{slug}', [FrontController::class, 'entidade_formadora'])->name('entidade_formadora');
Route::get('blog', [FrontController::class, 'blog'])->name('blog');
Route::get('blog/search',[FrontController::class, 'search'])->name('search');
Route::get('blog/{slug}', [FrontController::class, 'blogshow'])->name('blogshow');
Route::get('categories/{category:slug}',[FrontController::class, 'category'])->name('category');
Route::get('privadoCategories/{category:slug}',[FrontController::class, 'privadoCategory'])->name('privadoCategory');
Route::get('tags/{tag:slug}',[FrontController::class, 'tag'])->name('tag');
Route::get('pages/{slug}', [FrontController::class, 'page'])->name('page');
//Route::resource('entidades_formadoreas', 'Entidades_FormadoreasController');
//Route::resource('formadores', \App\Http\Controllers\FormadoresController::class);



Auth::routes([
    'register' => false
]);

Route::get('forget-password', [ForgotPasswordController::class, 'showForgetPasswordForm'])->name('forget.password.get');
Route::post('forget-password', [ForgotPasswordController::class, 'submitForgetPasswordForm'])->name('forget.password.post');
Route::get('reset-password/{token}', [ForgotPasswordController::class, 'showResetPasswordForm'])->name('reset.password.get');
Route::post('reset-password', [ForgotPasswordController::class, 'submitResetPasswordForm'])->name('reset.password.post');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['as'=>'admin.','prefix'=>'admin','middleware'=>'auth'],function () {
    Route::get('migrate', [FrontController::class, 'migrate'])->middleware('can:isAdmin')->name('migrate');
    Route::get('dashboard', [GeneralController::class, 'dashboard'])->name('dashboard');

    // General settings
    Route::get('general-settings', [GeneralController::class, 'general'])->middleware('can:isAdmin')->name('general');
    Route::post('general-settings', [GeneralController::class, 'generalUpdate'])->middleware('can:isAdmin')->name('general.update');

    // About
    Route::get('about', [GeneralController::class, 'about'])->middleware('can:isAdmin')->name('about');
    Route::post('about', [GeneralController::class, 'aboutUpdate'])->middleware('can:isAdmin')->name('about.update');

    // Manage Banner
    Route::get('banner', [BannerController::class, 'index'])->middleware('can:isAdmin')->name('banner');
    Route::get('banner/create', [BannerController::class, 'create'])->middleware('can:isAdmin')->name('banner.create');
    Route::post('banner/create', [BannerController::class, 'store'])->middleware('can:isAdmin')->name('banner.store');
    Route::get('banner/edit/{id}', [BannerController::class, 'edit'])->middleware('can:isAdmin')->name('banner.edit');
    Route::post('banner/edit/{id}', [BannerController::class, 'update'])->middleware('can:isAdmin')->name('banner.update');
    Route::delete('banner/destroy/{id}',[BannerController::class, 'destroy'])->middleware('can:isAdmin')->name('banner.destroy');

     // Manage Portfolio Categories
     Route::get('portfolio-categories', [PcategoryController::class, 'index'])->name('pcategory');
     Route::post('portfolio-categories', [PcategoryController::class, 'store'])->name('pcategory.store');
     Route::get('Portfolio-categories/edit/{id}', [PcategoryController::class, 'edit'])->name('pcategory.edit');
     Route::post('Portfolio-categories/edit/{id}', [PcategoryController::class, 'update'])->name('pcategory.update');
     Route::delete('Portfolio-categories/destroy/{id}',[PcategoryController::class, 'destroy'])->name('pcategory.destroy');

     // Manage asistent
//    Route::get('asistents', [AsistentController::class, 'index'])->name('asistent');
    Route::get('asistent/create/{id}', [AsistentController::class, 'create'])->name('asistent.create');
    Route::post('asistent/create', [AsistentController::class, 'store'])->name('asistent.store');
    Route::get('asistent/edit/{id}', [AsistentController::class, 'edit'])->name('asistent.edit');
    Route::get('asistent/export',[AsistentController::class, 'export'])->name('asistent.export');
    Route::post('asistent/edit/{id}', [AsistentController::class, 'update'])->name('asistent.update');
    Route::delete('asistent/destroy/{id}',[AsistentController::class, 'destroy'])->name('asistent.destroy');
    Route::get('operador/edit/{id}/{curso}', [AsistentController::class, 'show'])->name('operador.edit');
    Route::post('operador/edit/{id}', [AsistentController::class, 'updateOperador'])->name('operador.update');

    // Manage Portfolio
//    Route::resource('cursos',CursosController::class);
    Route::get('cursos', [CursosController::class, 'index'])->name('cursos');
    Route::get('inactiveCursos', [CursosController::class, 'index2'])->name('inactiveCursos');
    Route::get('cursos/create', [CursosController::class, 'create'])->name('cursos.create');
    Route::post('cursos/create', [CursosController::class, 'store'])->name('cursos.store');
    Route::get('cursos/edit/{id}', [CursosController::class, 'edit'])->name('cursos.edit');
    Route::post('cursos/edit/{id}', [CursosController::class, 'update'])->name('cursos.update');
    Route::post('cursos/activo/{id}',[CursosController::class, 'activo'])->name('cursos.activo');
    Route::get('cursos/export',[CursosController::class, 'export'])->name('cursos.export');
    Route::get('cursos/print/{id}',[CursosController::class, 'print'])->name('cursos.print');
    Route::get('cursos/prnpriview',[CursosController::class, 'prnpriview'])->name('cursos.prnpriview');
    Route::get('trashed-cursos', [CursosController::class, 'trashed'])->name('cursos.trashed');
    Route::delete('cursos/destroy/{id}',[CursosController::class, 'destroy'])->name('cursos.destroy');
    Route::post('cursos/force-delete', [CursosController::class,'forceDelete'])->name('cursos.force-delete');
    Route::post('cursos/restore', [CursosController::class,'restore'])->name('cursos.restore');
    Route::get('cursos/asistents/{cursos}',[CursosController::class, 'asistents'])->name('cursos.asistents');

//    Route::get('/cursos','PrintController@index');
//    Route::get('/prnpriview','PrintController@prnpriview');


    // Manage Categories
     Route::get('categories', [CategoryController::class, 'index'])->name('category');
     Route::get('categories/create', [CategoryController::class, 'create'])->name('category.create');
     Route::post('categories/create', [CategoryController::class, 'store'])->name('category.store');
     Route::get('categories/edit/{id}', [CategoryController::class, 'edit'])->name('category.edit');
     Route::post('categories/edit/{id}', [CategoryController::class, 'update'])->name('category.update');
     Route::delete('categories/destroy/{id}',[CategoryController::class, 'destroy'])->name('category.destroy');

     // Manage Tags
     Route::get('tags', [TagController::class, 'index'])->name('tag');
     Route::get('tags/create', [TagController::class, 'create'])->name('tag.create');
     Route::post('tags/create', [TagController::class, 'store'])->name('tag.store');
     Route::get('tags/edit/{id}', [TagController::class, 'edit'])->name('tag.edit');
     Route::post('tags/edit/{id}', [TagController::class, 'update'])->name('tag.update');
     Route::delete('tags/destroy/{id}',[TagController::class, 'destroy'])->name('tag.destroy');

     // Manage Blog
    Route::get('post',[PostController::class, 'index'])->middleware('can:isAdmin')->name('post');
    Route::get('post/create',[PostController::class, 'create'])->middleware('can:isAdmin')->name('post.create');

resources/views/admin/about.blade.php
@extends('layouts.admin')

@section('content')

@if (session('error'))
<div class="alert alert-danger">
    {{ session('error') }}
</div>
@endif
@if (session('success'))
<div class="alert alert-success">
    {{ session('success') }}
</div>
@endif

<form action="{{ route('about.update',1) }}" method="POST" enctype="multipart/form-data">
    @csrf

  <div class="form-group ml-5">
    <label for="title" class="col-sm-2 col-form-label">{{__('message.Title')}}</label>
    <div class="col-sm-7">
      <input type="text" name='title' class="form-control {{$errors->first('title') ? "is-invalid" : "" }} " value="{{old('title') ? old('title') : $about->title}}" id="link" placeholder="Title About">
      <div class="invalid-feedback">
        {{ $errors->first('title') }}    
    </div> 
    </div>
  </div>

  <div class="form-group ml-5">
    <label for="subject" class="col-sm-2 col-form-label">{{__('message.Slogan')}}</label>
    <div class="col-sm-7">
      <input type="text" name='subject' class="form-control {{$errors->first('subject') ? "is-invalid" : "" }} " value="{{old('subject') ? old('subject') : $about->subject}}" id="link" placeholder="Slogan">
      <div class="invalid-feedback">
        {{ $errors->first('subject') }}    
    </div> 
    </div>
  </div>
    
    <div class="form-group ml-5">
        <label for="desc" class="col-sm-2 col-form-label">{{__('message.Desc')}}</label>
        <div class="col-sm-7">
          <textarea name="desc" cols="30" rows="10" class="form-control {{$errors->first('desc') ? "is-invalid" : "" }} " id="summernote">{{old('desc') ? old('desc') : $about->desc}}</textarea>
          <div class="invalid-feedback">
            {{ $errors->first('desc') }}    
        </div> 
        </div>
      
    </div>
      
    <div class="form-group ml-5">
        <div class="col-sm-3">
            <button type="submit" class="btn btn-primary">{{__('message.Update')}}</button>
        </div>
    </div>
  </form>
@endsection

resources/views/admin/general.blade.php
@extends('layouts.admin')

@section('styles')
<style>
   .picture-container {
  position: relative;
  cursor: pointer;
  text-align: center;
}
 .picture {
  width: 800px;
  height: 400px;
  background-color: #999999;
  border: 4px solid #CCCCCC;
  color: #FFFFFF;
  /* border-radius: 50%; */
  margin: 5px auto;
  overflow: hidden;
  transition: all 0.2s;
  -webkit-transition: all 0.2s;
}
.picture:hover {
  border-color: #2ca8ff;
}
.picture input[type="file"] {
  cursor: pointer;
  display: block;
  height: 100%;
  left: 0;
  opacity: 0 !important;
  position: absolute;
  top: 0;
  width: 100%;
}
.picture-src {
  width: 100%;
  height: 100%;
}
</style>

@endsection

@section('content')

@if (session('success'))
<div class="alert alert-success">
    {{ session('success') }}
</div>
@endif

@if (session('error'))
<div class="alert alert-danger">
    {{ session('error') }}
</div>
@endif

<form action="{{ route('admin.general.update') }}" method="POST" enctype="multipart/form-data">
    @csrf

    <div class="container">

        <div class="form-group">

            <div class="picture-container">

                <div class="picture">

                    <img src="{{asset('storage/' . $general->logo)}}" class="picture-src" id="wizardPicturePreview" height="200px" width="400px" title=""/>

                    <input type="file" id="wizard-picture" name="logo" class="form-control {{$errors->first('logo') ? "is-invalid" : "" }} ">

                    <div class="invalid-feedback">
                        {{ $errors->first('logo') }}
                    </div>

                </div>

                <h6>{{__('message.Upload')}}</h6>

            </div>

        </div>

        <div class="form-group ml-5">

            <label for="favicon" class="col-sm-2 col-form-label">Favicon</label>

            <div class="col-sm-7">

                <img src="{{asset('storage/' . $general->favicon)}}" alt="">
                <input type="file" name='favicon' class="form-control {{$errors->first('favicon') ? "is-invalid" : "" }} " value="{{old('favicon') ? old('favicon') : $general->favicon}}" id="favicon" placeholder="Title">

                <div class="invalid-feedback">
                    {{ $errors->first('favicon') }}
                </div>

            </div>

        </div>

        <div class="form-group ml-5">

            <label for="title" class="col-sm-2 col-form-label">Title</label>

            <div class="col-sm-7">

                <input type="text" name='title' class="form-control {{$errors->first('title') ? "is-invalid" : "" }} " value="{{old('title') ? old('title') : $general->title}}" id="title" placeholder="Title">

                <div class="invalid-feedback">
                    {{ $errors->first('title') }}
                </div>

            </div>

        </div>

        <div class="form-group ml-5">

            <label for="address1" class="col-sm-2 col-form-label">Address 1</label>

            <div class="col-sm-7">

                <input type="text" name='address1' class="form-control {{$errors->first('address1') ? "is-invalid" : "" }} " value="{{old('address1') ? old('address1') : $general->address1}}" id="address1" placeholder="Address 1">

                <div class="invalid-feedback">
                    {{ $errors->first('address1') }}
                </div>

            </div>

        </div>

        <div class="form-group ml-5">

            <label for="address2" class="col-sm-2 col-form-label">Address 2</label>

            <div class="col-sm-7">

                <input type="text" name='address2' class="form-control {{$errors->first('address2') ? "is-invalid" : "" }} " value="{{old('address2') ? old('address2') : $general->address2}}" id="address2" placeholder="Address 2">

                <div class="invalid-feedback">
                    {{ $errors->first('address2') }}
                </div>

            </div>

        </div>

        <div class="form-group ml-5">

            <label for="email" class="col-sm-2 col-form-label">E-mail</label>

            <div class="col-sm-7">

                <input type="email" name='email' class="form-control {{$errors->first('email') ? "is-invalid" : "" }} " value="{{old('email') ? old('email') : $general->email}}" id="email" placeholder="Email">

                <div class="invalid-feedback">
                    {{ $errors->first('email') }}
                </div>

            </div>

        </div>

        <div class="form-group ml-5">

            <label for="phone" class="col-sm-2 col-form-label">Phone</label>

            <div class="col-sm-7">

                <input type="text" name='phone' class="form-control {{$errors->first('phone') ? "is-invalid" : "" }} " value="{{old('phone') ? old('phone') : $general->phone}}" id="phone" placeholder="098765432">

                <div class="invalid-feedback">
                    {{ $errors->first('phone') }}
                </div>

            </div>

        </div>

        <div class="form-group ml-5">

            <label for="twitter" class="col-sm-2 col-form-label">FAX</label>

            <div class="col-sm-7">

                <input type="text" name='twitter' class="form-control {{$errors->first('twitter') ? "is-invalid" : "" }} " value="{{old('twitter') ? old('twitter') : $general->twitter}}" id="twitter" placeholder="Twitter">

                <div class="invalid-feedback">
                    {{ $errors->first('twitter') }}
                </div>

            </div>

        </div>

{{--        <div class="form-group ml-5">--}}

{{--            <label for="facebook" class="col-sm-2 col-form-label">Facebook</label>--}}

{{--            <div class="col-sm-7">--}}

{{--                <input type="text" name='facebook' class="form-control {{$errors->first('facebook') ? "is-invalid" : "" }} " value="{{old('facebook') ? old('facebook') : $general->facebook}}" id="facebook" placeholder="Facebook">--}}

{{--                <div class="invalid-feedback">--}}
{{--                    {{ $errors->first('facebook') }}--}}
{{--                </div>--}}

{{--            </div>--}}

{{--        </div>--}}

{{--        <div class="form-group ml-5">--}}

{{--            <label for="instagram" class="col-sm-2 col-form-label">Instagram</label>--}}

{{--            <div class="col-sm-7">--}}

{{--                <input type="text" name='instagram' class="form-control {{$errors->first('instagram') ? "is-invalid" : "" }} " value="{{old('instagram') ? old('instagram') : $general->instagram}}" id="instagram" placeholder="Instagram">--}}

{{--                <div class="invalid-feedback">--}}
{{--                    {{ $errors->first('instagram') }}--}}
{{--                </div>--}}

{{--            </div>--}}

{{--        </div>--}}

{{--        <div class="form-group ml-5">--}}

{{--            <label for="linkedin" class="col-sm-2 col-form-label">Linkedin</label>--}}

{{--            <div class="col-sm-7">--}}

{{--                <input type="text" name='linkedin' class="form-control {{$errors->first('linkedin') ? "is-invalid" : "" }} " value="{{old('linkedin') ? old('linkedin') : $general->linkedin}}" id="linkedin" placeholder="Linkedin">--}}

{{--                <div class="invalid-feedback">--}}
{{--                    {{ $errors->first('linkedin') }}--}}
{{--                </div>--}}

{{--            </div>--}}

{{--        </div>--}}

{{--        <div class="form-group ml-5">--}}

{{--            <label for="gmaps" class="col-sm-2 col-form-label">Link Gmaps</label>--}}

{{--            <div class="col-sm-7">--}}

{{--                <input type="text" name='gmaps' class="form-control {{$errors->first('gmaps') ? "is-invalid" : "" }} " value="{{old('gmaps') ? old('gmaps') : $general->gmaps}}" id="gmaps" placeholder="Link Gmaps">--}}

{{--                <div class="invalid-feedback">--}}
{{--                    {{ $errors->first('gmaps') }}--}}
{{--                </div>--}}

{{--            </div>--}}

{{--        </div>--}}

{{--        <div class="form-group ml-5">--}}

{{--            <label for="tawkto" class="col-sm-2 col-form-label">Tawk to</label>--}}

{{--            <div class="col-sm-7">--}}

{{--                <textarea name="tawkto" id="tawkto" cols="30" rows="10" class="form-control {{$errors->first('tawkto') ? "is-invalid" : "" }} ">{{old('tawkto') ? old('tawkto') : $general->tawkto}}</textarea>--}}

{{--                <div class="invalid-feedback">--}}
{{--                    {{ $errors->first('tawkto') }}--}}
{{--                </div>--}}

{{--            </div>--}}

{{--        </div>--}}

{{--        <div class="form-group ml-5">--}}

{{--            <label for="disqus" class="col-sm-2 col-form-label">Disqus</label>--}}

{{--            <div class="col-sm-7">--}}

{{--                <textarea name="disqus" id="disqus" cols="30" rows="10" class="form-control {{$errors->first('disqus') ? "is-invalid" : "" }} ">{{old('disqus') ? old('disqus') : $general->disqus}}</textarea>--}}

{{--                <div class="invalid-feedback">--}}
{{--                    {{ $errors->first('disqus') }}--}}
{{--                </div>--}}

{{--            </div>--}}

{{--        </div>--}}

{{--        <div class="form-group ml-5">--}}

{{--            <label for="sharethis" class="col-sm-2 col-form-label">Sharethis</label>--}}

{{--            <div class="col-sm-7">--}}

{{--                <textarea name="sharethis" id="sharethis" cols="30" rows="10" class="form-control {{$errors->first('sharethis') ? "is-invalid" : "" }} ">{{old('sharethis') ? old('sharethis') : $general->sharethis}}</textarea>--}}

{{--                <div class="invalid-feedback">--}}
{{--                    {{ $errors->first('sharethis') }}--}}
{{--                </div>--}}

{{--            </div>--}}

{{--        </div>--}}

        <div class="form-group ml-5">

            <label for="gverification" class="col-sm-2 col-form-label">Google Verification</label>

            <div class="col-sm-7">

                <input type="text" name='gverification' class="form-control {{$errors->first('gverification') ? "is-invalid" : "" }} " value="{{old('gverification') ? old('gverification') : $general->gverification}}" id="footer" placeholder="Google Verification">

                <div class="invalid-feedback">
                    {{ $errors->first('gverification') }}
                </div>

            </div>

        </div>

        <div class="form-group ml-5">

            <label for="footer" class="col-sm-2 col-form-label">Footer</label>

            <div class="col-sm-7">

                <input type="text" name='footer' class="form-control {{$errors->first('footer') ? "is-invalid" : "" }} " value="{{old('footer') ? old('footer') : $general->footer}}" id="footer" placeholder="Footer">

                <div class="invalid-feedback">
                    {{ $errors->first('footer') }}
                </div>

            </div>

        </div>

        <div class="form-group ml-5">

            <label for="keyword" class="col-sm-2 col-form-label">Keyword</label>

            <div class="col-sm-7">

                <input type="text" name='keyword' class="form-control {{$errors->first('keyword') ? "is-invalid" : "" }} " value="{{old('keyword') ? old('keyword') : $general->keyword}}" id="keyword" placeholder="Keyword">

                <div class="invalid-feedback">
                    {{ $errors->first('keyword') }}
                </div>

            </div>

        </div>

        <div class="form-group ml-5">

            <label for="meta_desc" class="col-sm-2 col-form-label">Meta Desc</label>

            <div class="col-sm-7">

                <input type="text" name='meta_desc' class="form-control {{$errors->first('meta_desc') ? "is-invalid" : "" }} " value="{{old('meta_desc') ? old('meta_desc') : $general->meta_desc}}" id="meta_desc" placeholder="Meta Description">

                <div class="invalid-feedback">
                    {{ $errors->first('meta_desc') }}
                </div>

            </div>

        </div>

        <div class="form-group ml-5">

            <div class="col-sm-3">

                <button type="submit" class="btn btn-primary">{{__('message.Update')}}</button>

            </div>

        </div>

    </div>

  </form>
@endsection

@push('scripts')
<script>
    // Prepare the preview for profile picture
    $("#wizard-picture").change(function(){
      readURL(this);
  });
  //Function to show image before upload
function readURL(input) {
  if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
          $('#wizardPicturePreview').attr('src', e.target.result).fadeIn('slow');
      }
      reader.readAsDataURL(input.files[0]);
  }
}
</script>
@endpush