routes/web.php
<?php

use App\Http\Controllers\DocumentController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{Auth\ForgotPasswordController,
    BannerController,
    CarnetController,
    CertificadoController,
    EntidadesFormadoreasController,
    ExamenController,
    OperadoresController,
    CategoryController,
    AsistentController,
    FaqController,
    FrontController,
    GeneralController,
    LinkController,
    HorarioController,
    PartnerController,
    PcategoryController,
    CursosController,
    PostController,
    FormadoresController,
    TagController,
    TestimonialController,
    TeamController,
    UserController};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', [FrontController::class, 'home'])->name('homepage');
Route::post('/', [FrontController::class, 'subscribe'])->name('subscribe');
Route::get('about-us', [FrontController::class, 'about'])->name('about');
Route::get('quienes-somos', [FrontController::class, 'about2'])->name('about2');
Route::get('contact', [FrontController::class, 'contact'])->name('contact');
Route::get('entidades', [FrontController::class, 'entidades'])->name('entidades');
Route::get('testimonials', [FrontController::class, 'testi'])->name('testi');
Route::get('cursos', [FrontController::class, 'cursos'])->name('cursos');
Route::get('curso/{slug}', [FrontController::class, 'curso'])->name('curso');
Route::get('carnets', [FrontController::class, 'carnets'])->name('carnets');
Route::POST('searchcarnet', [FrontController::class, 'searchcarnet'])->name('searchcarnet');
Route::get('carnet/{slug}', [FrontController::class, 'carnet'])->name('carnet');
Route::get('partners', [FrontController::class, 'partners'])->name('partners');
Route::get('partner/{slug}', [FrontController::class, 'partner'])->name('partner');
Route::get('entidades_formadoras', [FrontController::class, 'entidades_formadoras'])->name('entidades_formadoras');
Route::get('entidade_formadora/{slug}', [FrontController::class, 'entidade_formadora'])->name('entidade_formadora');
Route::get('blog', [FrontController::class, 'blog'])->name('blog');
Route::get('blog/search',[FrontController::class, 'search'])->name('search');
Route::get('blog/{slug}', [FrontController::class, 'blogshow'])->name('blogshow');
Route::get('categories/{category:slug}',[FrontController::class, 'category'])->name('category');
Route::get('privadoCategories/{category:slug}',[FrontController::class, 'privadoCategory'])->name('privadoCategory');
Route::get('tags/{tag:slug}',[FrontController::class, 'tag'])->name('tag');
Route::get('pages/{slug}', [FrontController::class, 'page'])->name('page');
//Route::resource('entidades_formadoreas', 'Entidades_FormadoreasController');
//Route::resource('formadores', \App\Http\Controllers\FormadoresController::class);



Auth::routes([
    'register' => false
]);

Route::get('forget-password', [ForgotPasswordController::class, 'showForgetPasswordForm'])->name('forget.password.get');
Route::post('forget-password', [ForgotPasswordController::class, 'submitForgetPasswordForm'])->name('forget.password.post');
Route::get('reset-password/{token}', [ForgotPasswordController::class, 'showResetPasswordForm'])->name('reset.password.get');
Route::post('reset-password', [ForgotPasswordController::class, 'submitResetPasswordForm'])->name('reset.password.post');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['as'=>'admin.','prefix'=>'admin','middleware'=>'auth'],function () {
    Route::get('migrate', [FrontController::class, 'migrate'])->middleware('can:isAdmin')->name('migrate');
    Route::get('dashboard', [GeneralController::class, 'dashboard'])->name('dashboard');

    // General settings
    Route::get('general-settings', [GeneralController::class, 'general'])->middleware('can:isAdmin')->name('general');
    Route::post('general-settings', [GeneralController::class, 'generalUpdate'])->middleware('can:isAdmin')->name('general.update');

    // About
    Route::get('about', [GeneralController::class, 'about'])->middleware('can:isAdmin')->name('about');
    Route::post('about', [GeneralController::class, 'aboutUpdate'])->middleware('can:isAdmin')->name('about.update');

    // Manage Banner
    Route::get('banner', [BannerController::class, 'index'])->middleware('can:isAdmin')->name('banner');
    Route::get('banner/create', [BannerController::class, 'create'])->middleware('can:isAdmin')->name('banner.create');
    Route::post('banner/create', [BannerController::class, 'store'])->middleware('can:isAdmin')->name('banner.store');
    Route::get('banner/edit/{id}', [BannerController::class, 'edit'])->middleware('can:isAdmin')->name('banner.edit');
    Route::post('banner/edit/{id}', [BannerController::class, 'update'])->middleware('can:isAdmin')->name('banner.update');
    Route::delete('banner/destroy/{id}',[BannerController::class, 'destroy'])->middleware('can:isAdmin')->name('banner.destroy');

     // Manage Portfolio Categories
     Route::get('portfolio-categories', [PcategoryController::class, 'index'])->name('pcategory');
     Route::post('portfolio-categories', [PcategoryController::class, 'store'])->name('pcategory.store');
     Route::get('Portfolio-categories/edit/{id}', [PcategoryController::class, 'edit'])->name('pcategory.edit');
     Route::post('Portfolio-categories/edit/{id}', [PcategoryController::class, 'update'])->name('pcategory.update');
     Route::delete('Portfolio-categories/destroy/{id}',[PcategoryController::class, 'destroy'])->name('pcategory.destroy');

     // Manage asistent
//    Route::get('asistents', [AsistentController::class, 'index'])->name('asistent');
    Route::get('asistent/create/{id}', [AsistentController::class, 'create'])->name('asistent.create');
    Route::post('asistent/create', [AsistentController::class, 'store'])->name('asistent.store');
    Route::get('asistent/edit/{id}', [AsistentController::class, 'edit'])->name('asistent.edit');
    Route::get('asistent/export',[AsistentController::class, 'export'])->name('asistent.export');
    Route::post('asistent/edit/{id}', [AsistentController::class, 'update'])->name('asistent.update');
    Route::delete('asistent/destroy/{id}',[AsistentController::class, 'destroy'])->name('asistent.destroy');
    Route::get('operador/edit/{id}/{curso}', [AsistentController::class, 'show'])->name('operador.edit');
    Route::post('operador/edit/{id}', [AsistentController::class, 'updateOperador'])->name('operador.update');

    // Manage Portfolio
//    Route::resource('cursos',CursosController::class);
    Route::get('cursos', [CursosController::class, 'index'])->name('cursos');
    Route::get('inactiveCursos', [CursosController::class, 'index2'])->name('inactiveCursos');
    Route::get('cursos/create', [CursosController::class, 'create'])->name('cursos.create');
    Route::post('cursos/create', [CursosController::class, 'store'])->name('cursos.store');
    Route::get('cursos/edit/{id}', [CursosController::class, 'edit'])->name('cursos.edit');
    Route::post('cursos/edit/{id}', [CursosController::class, 'update'])->name('cursos.update');
    Route::post('cursos/activo/{id}',[CursosController::class, 'activo'])->name('cursos.activo');
    Route::get('cursos/export',[CursosController::class, 'export'])->name('cursos.export');
    Route::get('cursos/print/{id}',[CursosController::class, 'print'])->name('cursos.print');
    Route::get('cursos/prnpriview',[CursosController::class, 'prnpriview'])->name('cursos.prnpriview');
    Route::get('trashed-cursos', [CursosController::class, 'trashed'])->name('cursos.trashed');
    Route::delete('cursos/destroy/{id}',[CursosController::class, 'destroy'])->name('cursos.destroy');
    Route::post('cursos/force-delete', [CursosController::class,'forceDelete'])->name('cursos.force-delete');
    Route::post('cursos/restore', [CursosController::class,'restore'])->name('cursos.restore');
    Route::get('cursos/asistents/{cursos}',[CursosController::class, 'asistents'])->name('cursos.asistents');

//    Route::get('/cursos','PrintController@index');
//    Route::get('/prnpriview','PrintController@prnpriview');


    // Manage Categories
     Route::get('categories', [CategoryController::class, 'index'])->name('category');
     Route::get('categories/create', [CategoryController::class, 'create'])->name('category.create');
     Route::post('categories/create', [CategoryController::class, 'store'])->name('category.store');
     Route::get('categories/edit/{id}', [CategoryController::class, 'edit'])->name('category.edit');
     Route::post('categories/edit/{id}', [CategoryController::class, 'update'])->name('category.update');
     Route::delete('categories/destroy/{id}',[CategoryController::class, 'destroy'])->name('category.destroy');

     // Manage Tags
     Route::get('tags', [TagController::class, 'index'])->name('tag');
     Route::get('tags/create', [TagController::class, 'create'])->name('tag.create');
     Route::post('tags/create', [TagController::class, 'store'])->name('tag.store');
     Route::get('tags/edit/{id}', [TagController::class, 'edit'])->name('tag.edit');
     Route::post('tags/edit/{id}', [TagController::class, 'update'])->name('tag.update');
     Route::delete('tags/destroy/{id}',[TagController::class, 'destroy'])->name('tag.destroy');

     // Manage Blog
    Route::get('post',[PostController::class, 'index'])->middleware('can:isAdmin')->name('post');
    Route::get('post/create',[PostController::class, 'create'])->middleware('can:isAdmin')->name('post.create');

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;

    public function Posts()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Tag;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tag = Tag::orderBy('id','desc')->get();

        return view('admin.tag.index',compact('tag'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        \Validator::make($request->all(), [
            "name" => "required|unique:tags",
            "keyword" => "required",
            "meta_desc" => "required"     
        ])->validate();
        
        $tag = new Tag();
        $tag->name = $request->name;
        $tag->slug = \Str::slug($request->name);
        $tag->keyword = $request->keyword;
        $tag->meta_desc = $request->meta_desc;

        if ( $tag->save()) {

            return redirect()->route('admin.tag')->with('success', 'Data added successfully');
    
           } else {
               
            return redirect()->route('admin.tag')->with('error', 'Data failed to add');
    
           }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::findOrFail($id);
        return view('admin.tag.edit',compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        \Validator::make($request->all(), [
            "name" => "required|unique:tags",
            "keyword" => "required",
            "meta_desc" => "required"     
        ])->validate();
        
        $tag = Tag::findOrFail($id);
        $tag->name = $request->name;
        $tag->slug = \Str::slug($request->name);
        $tag->keyword = $request->keyword;
        $tag->meta_desc = $request->meta_desc;

        if ( $tag->save()) {

            return redirect()->route('admin.tag')->with('success', 'Data updated successfully');
    
           } else {
               
            return redirect()->route('admin.tag')->with('error', 'Data failed to update');
    
           }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tag = Tag::findOrFail($id);
        $tag->delete();

        return redirect()->route('admin.tag')->with('success', 'Data deleted successfully');
    }
}

resources/views/admin/tag/create.blade.php
@extends('layouts.admin')

@section('content')

@if (session('error'))
<div class="alert alert-danger">
    {{ session('error') }}
</div>
@endif

<form action="{{ route('admin.tag.store') }}" method="POST">
    @csrf

    <div class="container">

        <div class="form-group ml-5">

            <label for="name" class="col-sm-2 col-form-label">{{__('message.Name')}}</label>

            <div class="col-sm-7">

                <input type="text" name='name' class="form-control {{$errors->first('name') ? "is-invalid" : "" }} " value="{{old('name')}}" id="name" placeholder="{{__('message.Name')}}">

                <div class="invalid-feedback">
                    {{ $errors->first('name') }}
                </div>

            </div>

        </div>

        <div class="form-group ml-5">

            <label for="keyword" class="col-sm-2 col-form-label">{{__('message.Palabra clave')}}</label>

            <div class="col-sm-7">

                <input type="text" name='keyword' class="form-control {{$errors->first('keyword') ? "is-invalid" : "" }} " value="{{old('keyword')}}" id="keyword" placeholder="{{__('message.Palabra clave')}}">

                <div class="invalid-feedback">
                    {{ $errors->first('keyword') }}
                </div>

            </div>

        </div>

        <div class="form-group ml-5">

            <label for="meta_desc" class="col-sm-2 col-form-label">{{__('message.Meta Desc')}}</label>

            <div class="col-sm-7">

                <input type="text" name='meta_desc' class="form-control {{$errors->first('meta_desc') ? "is-invalid" : "" }} " value="{{old('meta_desc')}}" id="meta_desc" placeholder="{{__('message.Meta Desc')}}">

                <div class="invalid-feedback">
                    {{ $errors->first('meta_desc') }}
                </div>

            </div>

        </div>

        <div class="form-group ml-5">

            <div class="col-sm-3">

                <button type="submit" class="btn btn-primary">{{__('message.Create')}}</button>

            </div>

        </div>

    </div>

  </form>
@endsection

resources/views/admin/tag/edit.blade.php
@extends('layouts.admin')

@section('content')

@if (session('error'))
<div class="alert alert-danger">
    {{ session('error') }}
</div>
@endif

<form action="{{ route('admin.tag.update',$tag->id) }}" method="POST">
    @csrf

    <div class="container">

        <div class="form-group ml-5">

            <label for="name" class="col-sm-2 col-form-label">{{__('message.Name')}}</label>

            <div class="col-sm-7">

                <input type="text" name='name' class="form-control {{$errors->first('name') ? "is-invalid" : "" }} " value="{{old('name') ? old('name') : $tag->name}}" id="name" placeholder="{{__('message.Name')}}">

                <div class="invalid-feedback">
                    {{ $errors->first('name') }}
                </div>

            </div>

        </div>

        <div class="form-group ml-5">

            <label for="keyword" class="col-sm-2 col-form-label">{{__('message.Palabra clave')}}</label>

            <div class="col-sm-7">

                <input type="text" name='keyword' class="form-control {{$errors->first('keyword') ? "is-invalid" : "" }} " value="{{old('keyword') ? old('keyword') : $tag->keyword}}" id="keyword" placeholder="{{__('message.Palabra clave')}}">

                <div class="invalid-feedback">
                    {{ $errors->first('keyword') }}
                </div>

            </div>

        </div>

        <div class="form-group ml-5">

            <label for="meta_desc" class="col-sm-2 col-form-label">{{__('message.Meta Desc')}}</label>

            <div class="col-sm-7">

                <input type="text" name='meta_desc' class="form-control {{$errors->first('meta_desc') ? "is-invalid" : "" }} " value="{{old('meta_desc') ? old('meta_desc') : $tag->meta_desc}}" id="meta_desc" placeholder="{{__('message.Meta Desc')}}">

                <div class="invalid-feedback">
                    {{ $errors->first('meta_desc') }}
                </div>

            </div>

        </div>

        <div class="form-group ml-5">

            <div class="col-sm-3">

                <button type="submit" class="btn btn-primary">{{__('message.Update')}}</button>

            </div>

        </div>

    </div>

  </form>
@endsection

resources/views/admin/tag/index.blade.php
@extends('layouts.admin')

@section('styles')

<link href="{{ asset('admin/vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">

@endsection

@section('content')

<!-- Page Heading -->

<h1 class="h3 mb-2 text-gray-800">{{__('message.Tags')}}</h1>

@if (session('success'))

<div class="alert alert-success">

    {{ session('success') }}

</div>

@endif

<!-- DataTales Example -->

<div class="card shadow mb-4">

    <div class="card-header py-3">

        <a href="{{ route('admin.tag.create') }}" class="btn btn-success">{{__('message.Create tag')}}</a>

    </div>

    <div class="card-body">

        <div class="table-responsive">

            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">

                <thead>

                    <tr>

                        <th>{{__('message.num')}}.</th>

                        <th>{{__('message.Name')}}</th>

                        <th>{{__('message.Slug')}}</th>

                        <th>{{__('message.Palabra clave')}}</th>

                        <th>{{__('message.Meta Desc')}}</th>

                        <th>{{__('message.Option')}}</th>

                    </tr>

                </thead>

                <tbody>

                @php

                $no=0;

                @endphp

                @foreach ($tag as $tag)

                    <tr>

                        <td>{{ ++$no }}</td>

                        <td>{{ $tag->name }}</td>

                        <td>{{ $tag->slug }}</td>

                        <td>{{ $tag->keyword }}</td>

                        <td>{{ $tag->meta_desc }}</td>

                        <td>

                            <a href="{{route('admin.tag.edit', [$tag->id])}}" class="btn btn-info btn-sm">  <i class="fas fa-edit"></i>  </a>

                            <form method="POST" action="{{route('admin.tag.destroy', [$tag->id])}}" class="d-inline" onsubmit="return confirm('¿Borrar esta etiqueta permanentemente?')">

                                @csrf

                                <input type="hidden" name="_method" value="DELETE">

                                <button type="submit" value="Delete" class="btn btn-danger btn-sm">
                                    <i class='fas fa-trash-alt'></i>
                                </button>

                            </form>

                        </td>

                    </tr>

                    @endforeach

                </tbody>

            </table>

        </div>

    </div>

</div>

@endsection

@push('scripts')

<script src="{{ asset('admin/vendor/datatables/jquery.dataTables.min.js') }}"></script>

<script src="{{ asset('admin/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

<script src="{{ asset('admin/js/demo/datatables-demo.js') }}"></script>

@endpush