routes/web.php
<?php

use App\Http\Controllers\DocumentController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{Auth\ForgotPasswordController,
    BannerController,
    CarnetController,
    CertificadoController,
    EntidadesFormadoreasController,
    ExamenController,
    OperadoresController,
    CategoryController,
    AsistentController,
    FaqController,
    FrontController,
    GeneralController,
    LinkController,
    HorarioController,
    PartnerController,
    PcategoryController,
    CursosController,
    PostController,
    FormadoresController,
    TagController,
    TestimonialController,
    TeamController,
    UserController};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', [FrontController::class, 'home'])->name('homepage');
Route::post('/', [FrontController::class, 'subscribe'])->name('subscribe');
Route::get('about-us', [FrontController::class, 'about'])->name('about');
Route::get('quienes-somos', [FrontController::class, 'about2'])->name('about2');
Route::get('contact', [FrontController::class, 'contact'])->name('contact');
Route::get('entidades', [FrontController::class, 'entidades'])->name('entidades');
Route::get('testimonials', [FrontController::class, 'testi'])->name('testi');
Route::get('cursos', [FrontController::class, 'cursos'])->name('cursos');
Route::get('curso/{slug}', [FrontController::class, 'curso'])->name('curso');
Route::get('carnets', [FrontController::class, 'carnets'])->name('carnets');
Route::POST('searchcarnet', [FrontController::class, 'searchcarnet'])->name('searchcarnet');
Route::get('carnet/{slug}', [FrontController::class, 'carnet'])->name('carnet');
Route::get('partners', [FrontController::class, 'partners'])->name('partners');
Route::get('partner/{slug}', [FrontController::class, 'partner'])->name('partner');
Route::get('entidades_formadoras', [FrontController::class, 'entidades_formadoras'])->name('entidades_formadoras');
Route::get('entidade_formadora/{slug}', [FrontController::class, 'entidade_formadora'])->name('entidade_formadora');
Route::get('blog', [FrontController::class, 'blog'])->name('blog');
Route::get('blog/search',[FrontController::class, 'search'])->name('search');
Route::get('blog/{slug}', [FrontController::class, 'blogshow'])->name('blogshow');
Route::get('categories/{category:slug}',[FrontController::class, 'category'])->name('category');
Route::get('privadoCategories/{category:slug}',[FrontController::class, 'privadoCategory'])->name('privadoCategory');
Route::get('tags/{tag:slug}',[FrontController::class, 'tag'])->name('tag');
Route::get('pages/{slug}', [FrontController::class, 'page'])->name('page');
//Route::resource('entidades_formadoreas', 'Entidades_FormadoreasController');
//Route::resource('formadores', \App\Http\Controllers\FormadoresController::class);



Auth::routes([
    'register' => false
]);

Route::get('forget-password', [ForgotPasswordController::class, 'showForgetPasswordForm'])->name('forget.password.get');
Route::post('forget-password', [ForgotPasswordController::class, 'submitForgetPasswordForm'])->name('forget.password.post');
Route::get('reset-password/{token}', [ForgotPasswordController::class, 'showResetPasswordForm'])->name('reset.password.get');
Route::post('reset-password', [ForgotPasswordController::class, 'submitResetPasswordForm'])->name('reset.password.post');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['as'=>'admin.','prefix'=>'admin','middleware'=>'auth'],function () {
    Route::get('migrate', [FrontController::class, 'migrate'])->middleware('can:isAdmin')->name('migrate');
    Route::get('dashboard', [GeneralController::class, 'dashboard'])->name('dashboard');

    // General settings
    Route::get('general-settings', [GeneralController::class, 'general'])->middleware('can:isAdmin')->name('general');
    Route::post('general-settings', [GeneralController::class, 'generalUpdate'])->middleware('can:isAdmin')->name('general.update');

    // About
    Route::get('about', [GeneralController::class, 'about'])->middleware('can:isAdmin')->name('about');
    Route::post('about', [GeneralController::class, 'aboutUpdate'])->middleware('can:isAdmin')->name('about.update');

    // Manage Banner
    Route::get('banner', [BannerController::class, 'index'])->middleware('can:isAdmin')->name('banner');
    Route::get('banner/create', [BannerController::class, 'create'])->middleware('can:isAdmin')->name('banner.create');
    Route::post('banner/create', [BannerController::class, 'store'])->middleware('can:isAdmin')->name('banner.store');
    Route::get('banner/edit/{id}', [BannerController::class, 'edit'])->middleware('can:isAdmin')->name('banner.edit');
    Route::post('banner/edit/{id}', [BannerController::class, 'update'])->middleware('can:isAdmin')->name('banner.update');
    Route::delete('banner/destroy/{id}',[BannerController::class, 'destroy'])->middleware('can:isAdmin')->name('banner.destroy');

     // Manage Portfolio Categories
     Route::get('portfolio-categories', [PcategoryController::class, 'index'])->name('pcategory');
     Route::post('portfolio-categories', [PcategoryController::class, 'store'])->name('pcategory.store');
     Route::get('Portfolio-categories/edit/{id}', [PcategoryController::class, 'edit'])->name('pcategory.edit');
     Route::post('Portfolio-categories/edit/{id}', [PcategoryController::class, 'update'])->name('pcategory.update');
     Route::delete('Portfolio-categories/destroy/{id}',[PcategoryController::class, 'destroy'])->name('pcategory.destroy');

     // Manage asistent
//    Route::get('asistents', [AsistentController::class, 'index'])->name('asistent');
    Route::get('asistent/create/{id}', [AsistentController::class, 'create'])->name('asistent.create');
    Route::post('asistent/create', [AsistentController::class, 'store'])->name('asistent.store');
    Route::get('asistent/edit/{id}', [AsistentController::class, 'edit'])->name('asistent.edit');
    Route::get('asistent/export',[AsistentController::class, 'export'])->name('asistent.export');
    Route::post('asistent/edit/{id}', [AsistentController::class, 'update'])->name('asistent.update');
    Route::delete('asistent/destroy/{id}',[AsistentController::class, 'destroy'])->name('asistent.destroy');
    Route::get('operador/edit/{id}/{curso}', [AsistentController::class, 'show'])->name('operador.edit');
    Route::post('operador/edit/{id}', [AsistentController::class, 'updateOperador'])->name('operador.update');

    // Manage Portfolio
//    Route::resource('cursos',CursosController::class);
    Route::get('cursos', [CursosController::class, 'index'])->name('cursos');
    Route::get('inactiveCursos', [CursosController::class, 'index2'])->name('inactiveCursos');
    Route::get('cursos/create', [CursosController::class, 'create'])->name('cursos.create');
    Route::post('cursos/create', [CursosController::class, 'store'])->name('cursos.store');
    Route::get('cursos/edit/{id}', [CursosController::class, 'edit'])->name('cursos.edit');
    Route::post('cursos/edit/{id}', [CursosController::class, 'update'])->name('cursos.update');
    Route::post('cursos/activo/{id}',[CursosController::class, 'activo'])->name('cursos.activo');
    Route::get('cursos/export',[CursosController::class, 'export'])->name('cursos.export');
    Route::get('cursos/print/{id}',[CursosController::class, 'print'])->name('cursos.print');
    Route::get('cursos/prnpriview',[CursosController::class, 'prnpriview'])->name('cursos.prnpriview');
    Route::get('trashed-cursos', [CursosController::class, 'trashed'])->name('cursos.trashed');
    Route::delete('cursos/destroy/{id}',[CursosController::class, 'destroy'])->name('cursos.destroy');
    Route::post('cursos/force-delete', [CursosController::class,'forceDelete'])->name('cursos.force-delete');
    Route::post('cursos/restore', [CursosController::class,'restore'])->name('cursos.restore');
    Route::get('cursos/asistents/{cursos}',[CursosController::class, 'asistents'])->name('cursos.asistents');

//    Route::get('/cursos','PrintController@index');
//    Route::get('/prnpriview','PrintController@prnpriview');


    // Manage Categories
     Route::get('categories', [CategoryController::class, 'index'])->name('category');
     Route::get('categories/create', [CategoryController::class, 'create'])->name('category.create');
     Route::post('categories/create', [CategoryController::class, 'store'])->name('category.store');
     Route::get('categories/edit/{id}', [CategoryController::class, 'edit'])->name('category.edit');
     Route::post('categories/edit/{id}', [CategoryController::class, 'update'])->name('category.update');
     Route::delete('categories/destroy/{id}',[CategoryController::class, 'destroy'])->name('category.destroy');

     // Manage Tags
     Route::get('tags', [TagController::class, 'index'])->name('tag');
     Route::get('tags/create', [TagController::class, 'create'])->name('tag.create');
     Route::post('tags/create', [TagController::class, 'store'])->name('tag.store');
     Route::get('tags/edit/{id}', [TagController::class, 'edit'])->name('tag.edit');
     Route::post('tags/edit/{id}', [TagController::class, 'update'])->name('tag.update');
     Route::delete('tags/destroy/{id}',[TagController::class, 'destroy'])->name('tag.destroy');

     // Manage Blog
    Route::get('post',[PostController::class, 'index'])->middleware('can:isAdmin')->name('post');
    Route::get('post/create',[PostController::class, 'create'])->middleware('can:isAdmin')->name('post.create');

app/Models/Banner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Banner extends Model
{
    use HasFactory;
}

app/Http/Controllers/BannerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Banner;

class BannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $banner = Banner::all();
        return view ('admin.banner.index', [
            'banner' => $banner
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('admin.banner.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'portada' => 'required|max:2048',
            'título' => 'required',
        ]);
        $banner = new Banner();
        $banner->title  = $request->título;
//        $banner->link  = $request->link;
//        $banner->desc   = $request->desc;

        $cover = $request->file('portada');
        if($cover){
        $cover_path = $cover->store('images/banner', 'public');
        $banner->cover = $cover_path;
        }

        if ($banner->save()) {
            return redirect()->route('admin.banner')->with('success', 'Data added successfully');
           } else {
            return redirect()->route('admin.banner.create')->with('error', 'Data failed to add');

           }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $banner = Banner::findOrFail($id);
        return view ('admin.banner.edit', [
            'banner' => $banner
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'título' => 'required',
            'portada' => 'max:2048',
        ]);
        $banner = Banner::findOrFail($id);
        $banner->title  = $request->título;

        $new_cover = $request->file('cover');
        if($new_cover){
        if($banner->cover && file_exists(storage_path('app/public/' . $banner->cover))){
            \Storage::delete('public/'. $banner->cover);
        }

        $new_cover_path = $new_cover->store('images/banner', 'public');

        $banner->cover = $new_cover_path;
    }
    // dd($banner);
        if ($banner->update()) {
            return redirect()->route('admin.banner')->with('success', 'Data updated successfully');
           } else {
            return redirect()->route('admin.banner.edit')->with('error', 'Data failed to update');

           }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $banner = Banner::findOrFail($id);

        if ($banner->delete()) {
            if($banner->cover && file_exists(storage_path('app/public/' . $banner->cover))){
                \Storage::delete('public/'. $banner->cover);
            }
        }

        return redirect()->route('admin.banner')->with('success', 'Data deleted successfully');
    }
}

resources/views/admin/banner/create.blade.php
@extends('layouts.admin')

@section('styles')
<style>
   .picture-container {
  position: relative;
  cursor: pointer;
  text-align: center;
}
 .picture {
  width: 800px;
  height: 400px;
  background-color: #999999;
  border: 4px solid #CCCCCC;
  color: #FFFFFF;
  /* border-radius: 50%; */
  margin: 5px auto;
  overflow: hidden;
  transition: all 0.2s;
  -webkit-transition: all 0.2s;
}
.picture:hover {
  border-color: #2ca8ff;
}
.picture input[type="file"] {
  cursor: pointer;
  display: block;
  height: 100%;
  left: 0;
  opacity: 0 !important;
  position: absolute;
  top: 0;
  width: 100%;
}
.picture-src {
  width: 100%;
  height: 100%;
}
</style>

@endsection

@section('content')

@if (session('error'))
<div class="alert alert-danger">
    {{ session('error') }}
</div>
@endif

<form action="{{ route('admin.banner.store') }}" method="POST" enctype="multipart/form-data">
    @csrf

    <div class="form-group">

        <div class="picture-container">
            <span class="maxsize"> El tamaño máximo de archivo subido no debe superar 2 MB</span>
            <div class="picture">

                <img src="" class="picture-src" id="wizardPicturePreview" height="200px" width="400px" title=""/>

                <input type="file" id="wizard-picture" name="portada" class=" {{$errors->first('portada') ? "is-invalid" : "" }} ">
                <div class="invalid-feedback" style="position: absolute;right: 0;bottom: -20px;">
                    {{ $errors->first('portada') }}
                </div>
            </div>


            <h6>{{__('message.Cover')}}</h6>

        </div>

      </div>

      <div class="form-group ml-5">
        <label for="título" class="col-sm-2 col-form-label">{{__('message.Title')}}</label>
        <div class="col-sm-7">
            <input type="text" name='título' class="form-control {{$errors->first('título') ? "is-invalid" : "" }} " value="{{old('título')}}" id="título" placeholder="título">
            <div class="invalid-feedback">
                {{ $errors->first('título') }}
            </div>
        </div>
    </div>

{{--    <div class="form-group ml-5">--}}
{{--        <label for="desc" class="col-sm-2 col-form-label">Desc</label>--}}
{{--        <div class="col-sm-7">--}}
{{--          <textarea name="desc" id="desc" cols="30" rows="10" class="form-control {{$errors->first('desc') ? "is-invalid" : "" }} " id="summernote">{{old('desc')}}</textarea>--}}
{{--          <div class="invalid-feedback">--}}
{{--            {{ $errors->first('desc') }}--}}
{{--        </div>--}}
{{--        </div>--}}
{{--    </div>--}}

{{--    <div class="form-group ml-5">--}}
{{--        <label for="link" class="col-sm-2 col-form-label">Link</label>--}}
{{--        <div class="col-sm-7">--}}
{{--          <input type="text" name='link' class="form-control {{$errors->first('link') ? "is-invalid" : "" }} " value="{{old('link')}}" id="link" placeholder="Link">--}}
{{--          <div class="invalid-feedback">--}}
{{--            {{ $errors->first('link') }}--}}
{{--        </div>--}}
{{--        </div>--}}
{{--      </div>--}}

    <div class="form-group ml-5">
        <div class="col-sm-3">
            <button type="submit" class="btn btn-primary">{{__('message.Create')}}</button>
        </div>
    </div>
  </form>
@endsection

@push('scripts')
<script>
    // Prepare the preview for profile picture
    $("#wizard-picture").change(function(){
      readURL(this);
  });
  //Function to show image before upload
function readURL(input) {
  if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
          $('#wizardPicturePreview').attr('src', e.target.result).fadeIn('slow');
      }
      reader.readAsDataURL(input.files[0]);
  }
}
</script>

@endpush

resources/views/admin/banner/edit.blade.php
@extends('layouts.admin')

@section('styles')
<style>
   .picture-container {
  position: relative;
  cursor: pointer;
  text-align: center;
}
 .picture {
  width: 800px;
  height: 400px;
  background-color: #999999;
  border: 4px solid #CCCCCC;
  color: #FFFFFF;
  /* border-radius: 50%; */
  margin: 5px auto;
  overflow: hidden;
  transition: all 0.2s;
  -webkit-transition: all 0.2s;
}
.picture:hover {
  border-color: #2ca8ff;
}
.picture input[type="file"] {
  cursor: pointer;
  display: block;
  height: 100%;
  left: 0;
  opacity: 0 !important;
  position: absolute;
  top: 0;
  width: 100%;
}
.picture-src {
  width: 100%;
  height: 100%;
}
</style>

@endsection

@section('content')

@if (session('error'))
<div class="alert alert-danger">
    {{ session('error') }}
</div>
@endif

<form action="{{ route('admin.banner.update',$banner->id) }}" method="POST" enctype="multipart/form-data">
    @csrf

    <div class="form-group">

        <div class="picture-container">
            <span class="maxsize"> El tamaño máximo de archivo subido no debe superar 2 MB</span>
            <div class="picture">

                <img src="{{ asset('storage/'.$banner->cover) }}" class="picture-src" id="wizardPicturePreview" height="200px" width="400px" title=""/>

                <input type="file" id="wizard-picture" name="cover">

            </div>

            <h6>{{__('message.Cover')}}</h6>

        </div>

      </div>

      <div class="form-group ml-5">
        <label for="título" class="col-sm-2 col-form-label">{{__('message.Title')}}</label>
        <div class="col-sm-7">
            <input type="text" name='título' class="form-control {{$errors->first('título') ? "is-invalid" : "" }} " value="{{old('título') ? old('título') : $banner->title}}" id="título" placeholder="título">
            <div class="invalid-feedback">
                {{ $errors->first('título') }}
            </div>
        </div>
    </div>

{{--    <div class="form-group ml-5">--}}
{{--        <label for="desc" class="col-sm-2 col-form-label">Desc</label>--}}
{{--        <div class="col-sm-7">--}}
{{--          <textarea name="desc" id="desc" cols="30" rows="10" class="form-control {{$errors->first('desc') ? "is-invalid" : "" }} ">{{old('desc') ? old('desc') : $banner->desc}}</textarea>--}}
{{--          <div class="invalid-feedback">--}}
{{--            {{ $errors->first('desc') }}    --}}
{{--        </div> --}}
{{--        </div>--}}
{{--      --}}
{{--    </div>--}}

{{--    <div class="form-group ml-5">--}}
{{--      <label for="link" class="col-sm-2 col-form-label">Link</label>--}}
{{--      <div class="col-sm-7">--}}
{{--        <input type="text" name='link' class="form-control {{$errors->first('link') ? "is-invalid" : "" }} " value="{{old('link') ? old('link') : $banner->link}}" id="link" placeholder="Link">--}}
{{--        <div class="invalid-feedback">--}}
{{--          {{ $errors->first('link') }}    --}}
{{--      </div> --}}
{{--      </div>--}}
{{--    </div>--}}

    <div class="form-group ml-5">
        <div class="col-sm-3">
            <button type="submit" class="btn btn-primary">{{__('message.Update')}}</button>
        </div>
    </div>
  </form>
@endsection

@push('scripts')
<script>
    // Prepare the preview for profile picture
    $("#wizard-picture").change(function(){
      readURL(this);
  });
  //Function to show image before upload
function readURL(input) {
  if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
          $('#wizardPicturePreview').attr('src', e.target.result).fadeIn('slow');
      }
      reader.readAsDataURL(input.files[0]);
  }
}
</script>

@endpush

resources/views/admin/banner/index.blade.php
@extends('layouts.admin')

@section('content')
      <!-- Begin Page Content -->
      <div class="container-fluid">
         <!-- Page Heading -->
         <h1 class="h3 mb-2 text-gray-800">{{__('message.banners')}}</h1>
         @if (session('success'))
         <div class="alert alert-success">
            {{ session('success') }}
        </div>
        @endif
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
           <a href="{{ route('admin.banner.create') }}" class="btn btn-primary btn-md">{{__('message.add new Banner')}}</a>
          </div>
          <div class="card-body">
              <h4>Las dimensiones de la foto deben ser 1700 * 1134 o lo que se adapte a estas dimensiones & El tamaño de la imagen debe ser inferior a 2 MB.</h4>
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>{{__('message.num')}}.</th>
                    <th>{{__('message.Cover')}}</th>
                    <th>{{__('message.Title')}}</th>
                    <th>{{__('message.Option')}}</th>
                  </tr>
                </thead>
                <tbody>
                    @php
                    $no=0;
                    @endphp
                @foreach ($banner as $banner)
                  <tr>
                    <td>{{ ++$no }}</td>
                    <td>
                        <img src="{{ asset('storage/'.$banner->cover) }}" alt="" height="200px" width="250px">
                    </td>
                    <td>{{ $banner->title }}</td>
                    <td>
                        <a href="{{route('admin.banner.edit', [$banner->id])}}" class="btn btn-info btn-sm"> <i class="fas fa-edit"></i> </a>

                        <form method="POST" action="{{route('admin.banner.destroy', [$banner->id])}}" class="d-inline" onsubmit="return confirm('¿Borrar este banner permanentemente?')">

                            @csrf

                            <input type="hidden" name="_method" value="DELETE">

                            <button type="submit" value="Delete" class="btn btn-danger btn-sm">
                                <i class='fas fa-trash-alt'></i>
                            </button>

                        </form>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>
      <!-- /.container-fluid -->
@endsection